services:
  - type: web
    name: ai-calling-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python twiml_server.py
    envVars:
      - key: PORT
        value: 10000
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
    healthCheckPath: /health
    healthCheckTimeoutSeconds: 30
    healthCheckIntervalSeconds: 60
    healthCheckThreshold: 3
    autoDeploy: true
    plan: free 